bots/urls.py
#~ from django.conf.urls.defaults import patterns,include   #depreciated in 1.5
from django.conf.urls import patterns,include,url           #does not work in django 1.3
from django.contrib import admin
#~ from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required,user_passes_test
import views

admin.autodiscover()
staff_required = user_passes_test(lambda u: u.is_staff)
superuser_required = user_passes_test(lambda u: u.is_superuser)
run_permission = user_passes_test(lambda u: u.has_perm('bots.change_mutex'))

urlpatterns = patterns('',
    url(r'^login.*', 'django.contrib.auth.views.login', {'template_name': 'admin/login.html'}),
    url(r'^logout.*', 'django.contrib.auth.views.logout',{'next_page': '/'}),
    url(r'^password_change/$', 'django.contrib.auth.views.password_change', name='password_change'),
    url(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done',name='password_change_done'),
    #login required
    url(r'^home.*', login_required(views.home)),
    url(r'^incoming.*', login_required(views.incoming)),
    url(r'^detail.*', login_required(views.detail)),
    url(r'^process.*', login_required(views.process)),
    url(r'^outgoing.*', login_required(views.outgoing)),
    url(r'^document.*', login_required(views.document)),
    url(r'^reports.*', login_required(views.reports)),
    url(r'^confirm.*', login_required(views.confirm)),
    url(r'^filer.*', login_required(views.filer)),
    url(r'^srcfiler.*', login_required(views.srcfiler)),
    #only staff
    url(r'^admin/$', login_required(views.home)),  #do not show django admin root page
    url(r'^admin/bots/$', login_required(views.home)),  #do not show django admin root page
    url(r'^admin/', include(admin.site.urls)),
    url(r'^runengine.+', run_permission(views.runengine)),
    #only superuser
    url(r'^delete.*', superuser_required(views.delete)),
    url(r'^plugin/index.*', superuser_required(views.plugin_index)),
    url(r'^plugin.*', superuser_required(views.plugin)),
    url(r'^plugout/index.*', superuser_required(views.plugout_index)),
    url(r'^plugout/backup.*', superuser_required(views.plugout_backup)),
    url(r'^plugout.*', superuser_required(views.plugout)),
    url(r'^sendtestmail.*', superuser_required(views.sendtestmailmanagers)),
    #catch-all
    url(r'^.*', 'bots.views.index'),
    )

handler500 = 'bots.views.server_error'

bots/models.py
''' Declare database tabels. 
    Django is not always perfect in generating db - but improving ;-)). 
    The generated database can be manipulated SQL. see bots/sql/*.
'''
import os
import urllib
import re
from django.db import models
from django.utils.translation import ugettext_lazy as _     #djnago 1.7: have to use ugettext_lazy here
#~ from django.core.validators import validate_email
from django.core.validators import validate_integer
from django.core.exceptions import ValidationError
import botsglobal
import validate_email
#***Declare constants, mostly codelists.**********************************************
DEFAULT_ENTRY = ('',"---------")
STATUST = [
    (0, _(u'Open')),
    (1, _(u'Error')),
    (2, _(u'Stuck')),
    (3, _(u'Done')),
    (4, _(u'Resend')),
    (5, _(u'No retry')),
    ]
STATUS = [
    (1,_(u'Process')),
    (3,_(u'Discarded')),
    (200,_(u'Received')),
    (220,_(u'Infile')),
    (310,_(u'Parsed')),
    (320,_(u'Document-in')),
    (330,_(u'Document-out')),
    (400,_(u'Merged')),
    (500,_(u'Outfile')),
    (520,_(u'Send')),
    ]
EDITYPES = [
    #~ DEFAULT_ENTRY,
    ('csv', _(u'csv')),
    ('database', _(u'database (old)')),
    ('db', _(u'db')),
    ('edifact', _(u'edifact')),
    ('email-confirmation',_(u'email-confirmation')),
    ('excel',_(u'excel (only incoming)')),
    ('fixed', _(u'fixed')),
    ('idoc', _(u'idoc')),
    ('json', _(u'json')),
    ('jsonnocheck', _(u'jsonnocheck')),
    ('mailbag', _(u'mailbag')),
    ('raw', _(u'raw')),
    ('templatehtml', _(u'template-html')),
    ('tradacoms', _(u'tradacoms')),
    ('xml', _(u'xml')),
    ('xmlnocheck', _(u'xmlnocheck')),
    ('x12', _(u'x12')),
    ]
INOROUT = (
    ('in', _(u'in')),
    ('out', _(u'out')),
    )
CHANNELTYPE = (     #Note: in communication.py these channeltypes are converted to channeltype to use in acceptance tests.
    ('file', _(u'file')),
    ('smtp', _(u'smtp')),
    ('smtps', _(u'smtps')),
    ('smtpstarttls', _(u'smtpstarttls')),
    ('pop3', _(u'pop3')),
    ('pop3s', _(u'pop3s')),
    ('pop3apop', _(u'pop3apop')),
    ('http', _(u'http')),
    ('https', _(u'https')),
    ('imap4', _(u'imap4')),
    ('imap4s', _(u'imap4s')),
    ('ftp', _(u'ftp')),
    ('ftps', _(u'ftps (explicit)')),
    ('ftpis', _(u'ftps (implicit)')),
    ('sftp', _(u'sftp (ssh)')),
    ('xmlrpc', _(u'xmlrpc')),
    ('mimefile', _(u'mimefile')),
    ('trash', _(u'trash/discard')),
    ('communicationscript', _(u'communicationscript')),
    ('db', _(u'db')),
    ('database', _(u'database (old)')),
    )
CONFIRMTYPE = [
    ('ask-email-MDN',_(u'ask an email confirmation (MDN) when sending')),
    ('send-email-MDN',_(u'send an email confirmation (MDN) when receiving')),
    ('ask-x12-997',_(u'ask a x12 confirmation (997) when sending')),
    ('send-x12-997',_(u'send a x12 confirmation (997) when receiving')),
    ('ask-edifact-CONTRL',_(u'ask an edifact confirmation (CONTRL) when sending')),
    ('send-edifact-CONTRL',_(u'send an edifact confirmation (CONTRL) when receiving')),
    ]
RULETYPE = (
    ('all',_(u'Confirm all')),
    ('route',_(u'Route')),
    ('channel',_(u'Channel')),
    ('frompartner',_(u'Frompartner')),
    ('topartner',_(u'Topartner')),
    ('messagetype',_(u'Messagetype')),
    )
ENCODE_MIME = (
    ('always',_(u'Base64')),
    ('never',_(u'Never')),
    ('ascii',_(u'Base64 if not ascii')),
    )
EDI_AS_ATTACHMENT = (
    ('attachment',_(u'As attachment')),
    ('body',_(u'In body of email')),
    )
ENCODE_ZIP_IN = (
    (1,_(u'Always unzip file')),
    (2,_(u'If zip-file: unzip')),
    )
ENCODE_ZIP_OUT = (
    (1,_(u'Always zip')),
    )
TRANSLATETYPES = (
    (0,_(u'Nothing')),
    (1,_(u'Translate')),
    (2,_(u'Pass-through')),
    (3,_(u'Parse & Pass-through')),
    )
CONFIRMTYPELIST = [DEFAULT_ENTRY] + CONFIRMTYPE
EDITYPESLIST = [DEFAULT_ENTRY] + EDITYPES

#***Functions that produced codelists.**********************************************
def getroutelist():     #needed because the routeid is needed (and this is not theprimary key
    return [DEFAULT_ENTRY]+[(l,l) for l in routes.objects.values_list('idroute', flat=True).order_by('idroute').distinct() ]

def getinmessagetypes():
    return [DEFAULT_ENTRY]+[(l,l) for l in translate.objects.values_list('frommessagetype', flat=True).order_by('frommessagetype').distinct() ]
def getoutmessagetypes():
    return [DEFAULT_ENTRY]+[(l,l) for l in translate.objects.values_list('tomessagetype', flat=True).order_by('tomessagetype').distinct() ]
def getallmessagetypes():
    return [DEFAULT_ENTRY]+[(l,l) for l in sorted(set(list(translate.objects.values_list('tomessagetype', flat=True).all()) + list(translate.objects.values_list('frommessagetype', flat=True).all()) )) ]
def getpartners():
    return [DEFAULT_ENTRY]+[(l,'%s (%s)'%(l,n)) for (l,n) in partner.objects.values_list('idpartner','name').filter(active=True)]
def getfromchannels():
    return [DEFAULT_ENTRY]+[(l,'%s (%s)'%(l,t)) for (l,t) in channel.objects.values_list('idchannel','type').filter(inorout='in')]
def gettochannels():
    return [DEFAULT_ENTRY]+[(l,'%s (%s)'%(l,t)) for (l,t) in channel.objects.values_list('idchannel','type').filter(inorout='out')]

#***Database tables that produced codelists.**********************************************
class StripCharField(models.CharField):
    ''' strip values before saving to database. this is not default in django #%^&*'''
    def get_prep_value(self, value,*args,**kwargs):
        ''' Convert Python objects (value) to query values (returned)
        ''' 
        if isinstance(value, basestring):
            return value.strip()
        else:
            return value

def multiple_email_validator(value):
    ''' Problems with validating email adresses:
        django's email validating is to strict. (eg if quoted user part, space is not allowed).
        use case: x400 via IPmail (x400 addresses are used in email-addresses).
        Use re-expressions to get this better/conform email standards.
    '''
    if botsglobal.ini.getboolean('webserver','use_email_address_validation',True):      #tric to disable email validation via bots.ini
        emails = re.split(',(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)',value)    #split emails
        for email in emails:
            if not validate_email.validate_email_address(email):
                raise ValidationError(_(u'Enter valid e-mail address(es) separated by commas.'), code='invalid')

def script_link1(script,linktext):
    ''' if script exists return a plain text name as link; else return "no" icon, plain text name
        used in translate (all scripts should exist, missing script is an error).
    '''
    if os.path.exists(script):
        return '<a href="/srcfiler/?src=%s" target="_blank">%s</a>'%(urllib.quote(script.encode("utf-8")),linktext)
    else:
        return '<img src="/media/admin/img/icon-no.gif"></img> %s'%linktext

def script_link2(script):
    ''' if script exists return "yes" icon + view link; else return "no" icon
        used in routes, channels (scripts are optional)
    '''
    if os.path.exists(script):
        return '<a class="nowrap" href="/srcfiler/?src=%s" target="_blank"><img src="/media/admin/img/icon-yes.gif"></img> view</a>'%urllib.quote(script.encode("utf-8"))
    else:
        return '<img src="/media/admin/img/icon-no.gif"></img>'


class MultipleEmailField(models.CharField):
    default_validators = [multiple_email_validator]
    description = _('One or more e-mail address(es),separated by ",".')
class TextAsInteger(models.CharField):
    default_validators = [validate_integer]

#***********************************************************************************
#******** written by webserver ********************************************************
#***********************************************************************************
class confirmrule(models.Model):
    #~ id = models.IntegerField(primary_key=True)
    active = models.BooleanField(default=False)
    confirmtype = StripCharField(max_length=35,choices=CONFIRMTYPE)
    ruletype = StripCharField(max_length=35,choices=RULETYPE)
    negativerule = models.BooleanField(default=False,help_text=_(u'Use to exclude. Bots first checks positive rules, than negative rules. Eg include certain channel, exclude partner XXX.'))
    frompartner = models.ForeignKey('partner',related_name='cfrompartner',null=True,on_delete=models.CASCADE,blank=True,limit_choices_to = {'isgroup': False})
    topartner = models.ForeignKey('partner',related_name='ctopartner',null=True,on_delete=models.CASCADE,blank=True,limit_choices_to = {'isgroup': False})
    idroute = StripCharField(max_length=35,null=True,blank=True,verbose_name=_(u'route'))
    idchannel = models.ForeignKey('channel',null=True,on_delete=models.CASCADE,blank=True,verbose_name=_(u'channel'))
    editype = StripCharField(max_length=35,choices=EDITYPES,blank=True)         #20121229"is not used anymore.....editype is always clear from context.
    messagetype = StripCharField(max_length=35,blank=True,help_text=_(u'Eg "850004010" (x12) or "ORDERSD96AUN" (edifact).'))
    rsrv1 = StripCharField(max_length=35,blank=True,null=True)  #added 20100501
    rsrv2 = models.IntegerField(null=True)                        #added 20100501
    def __unicode__(self):
        return unicode(self.confirmtype) + u' ' + unicode(self.ruletype)
    class Meta:
        db_table = 'confirmrule'
        verbose_name = _(u'confirm rule')
        ordering = ['confirmtype','ruletype','negativerule','frompartner','topartner','idroute','idchannel','messagetype']
class ccodetrigger(models.Model):
    ccodeid = StripCharField(primary_key=True,max_length=35,verbose_name=_(u'Type of user code'))
    ccodeid_desc = models.TextField(blank=True,null=True,verbose_name=_(u'Description'))
    def __unicode__(self):
        return unicode(self.ccodeid)
    class Meta:
        db_table = 'ccodetrigger'
        verbose_name = _(u'user code type')
        ordering = ['ccodeid']
class ccode(models.Model):

bots/templates/bots/about.html
{% extends "admin/base.html" %}
{% load i18n %}

{% block content %}
<table id="about">
    <tr>
        <td>
        <h1>{% trans 'Bots Open Source EDI Translator' %}</h1>
        <br/>
        <a target="_blank" href="http://code.google.com/p/bots/wiki/StartIntroduction">{% trans 'Bots documentation' %}</a><br/>
        <a target="_blank" href="http://groups.google.com/group/botsmail">{% trans 'Bots mailing list' %}</a><br/>
        <a target="_blank" href="http://www.ebbersconsult.com">{% trans 'Commercial support by EbbersConsult' %}</a><br/>
        <br/>
        </td>
        <td></td>
    </tr>
    <tr>
        <td>{% trans 'Current user' %}</td><td>{{ user.username }}</td>
    </tr>
    <tr>
        <td>{% trans 'Last login' %}</td><td>{{ user.last_login|date:"Y-m-d G:i" }}</td>
    </tr>
    {% for key, value in botsinfo %}
        {% if value %}
        <tr>
            <td>{{ key|lower|capfirst }}</td><td>{{ value }}</td>
        </tr>
        {% endif %}
    {% endfor %}
</table>
{% endblock %}

bots/templates/bots/confirm.html
{% extends "admin/base.html" %}
{% load i18n %}
{% load botsfilters %}


{% block content %}
<form action="{{ form.action }}" method="post">{% csrf_token %}
    <input onClick="history.back()" type="button" value="{% trans 'Back' %}" />
    <input type="submit" name="2select" value="{% trans 'Change selection' %}" />
    <input type="submit" name="2incoming" value="{% trans 'Incoming (same selection)' %}" />
    <input type="submit" name="2outgoing" value="{% trans 'Outgoing (same selection)' %}" />
    {% include "bots/paginator.html" %}

    <table id="botstable">
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <thead>
            <tr>
                <th></th>
                <th><button class="botsheader" type="submit" name="order" value="ts" >{% trans 'Date/time' %}</button></th>
                <th><button class="botsheader" type="submit" name="order" value="filename" >{% trans 'File' %}</button></th>
                <th><button class="botsheader" type="submit" name="order" value="confirmtype" title="">{% trans 'ConfirmType' %}</button></th>
                <th><button class="botsheader" >{% trans 'ConfirmFile' %}</button></th>
                <th><button class="botsheader" type="submit" name="order" value="editype" >{% trans 'Editype' %}</button></th>
                <th><button class="botsheader" type="submit" name="order" value="messagetype" >{% trans 'Messagetype' %}</button></th>
                <th><button class="botsheader" type="submit" name="order" value="idroute" >{% trans 'Route' %}</button></th>
                <th><button class="botsheader" type="submit" name="order" value="fromchannel" >{% trans 'FromChannel' %}</button></th>
                <th><button class="botsheader" type="submit" name="order" value="tochannel" >{% trans 'ToChannel' %}</button></th>
                <th><button class="botsheader" type="submit" name="order" value="frompartner" >{% trans 'FromPartner' %}</button></th>
                <th><button class="botsheader" type="submit" name="order" value="topartner" >{% trans 'ToPartner' %}</button></th>
                <th><button class="botsheader" type="submit" name="order" value="reference" >{% trans 'Reference' %}</button></th>
            </tr>
        </thead>
        <tbody>
        {% for row in queryset.object_list %}
            <tr class="{% cycle 'row1' 'row2' %}">
                <td>
                    <div class="dropdown"><img class="action" src="/media/images/star.png" />
                        <ul>
                            <li><button class="botsheader" onclick="document.location.href='/detail/?outidta={{row.idta}}'; return false;">{% trans 'View detail' %}</button></li>
                            <li><button class="botsheader" type="submit" name="confirm" value="{{row.idta}}" >{% trans 'Confirm manual' %}</button></li>
                        </ul>
                    </div>
                </td>
                <td class="nowrap">{{row.ts|date:"Y-m-d H:i:s"}}</td>
                <td><a href="/filer/?action=this&amp;idta={{row.idta}}" target="_blank" class="botslink">{{row.filename|shortpath}}</a></td>
                <td>{{row.confirmtype}}</td>
                <td>{% if row.confirmidta > 0 %}
                        <a href="/filer/?action=this&amp;idta={{row.confirmidta}}" target="_blank" class="botslink">{{row.confirmidta}}</a>
                    {% else  %}
                        {% if row.confirmidta %}
                            {% trans 'Manual confirm' %}
                        {% endif %}
                    {% endif %}</td>
                <td class="nowrap">{{row.editype}}</td>
                <td class="nowrap">{{row.messagetype}}</td>
                <td class="nowrap">{{row.idroute}}</td>
                <td class="nowrap">{{row.fromchannel}}</td>
                <td class="nowrap">{{row.tochannel}}</td>
                <td class="nowrap">{{row.frompartner}}</td>
                <td class="nowrap">{{row.topartner}}</td>
                <td class="nowrap">{{row.reference}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</form>
{% endblock %}

bots/templates/bots/delete.html
{% extends "admin/base.html" %}
{% load i18n %}

<div id="menu">

{% block content %}
<br/>
<h1>Bulk delete from configuration, user scripts etc.</h1>
<p>&nbsp;!Deletions can NOT be undone!</p>
<br/>
<form action="/delete" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <table>
        {{ form }}
    </table>
    <br/>&nbsp;
    <input type="submit" name="cancel" value="{% trans 'Cancel' %}" />
    <input type="submit" name="submit" value="{% trans 'Bulk delete' %}" />
</form>
{% endblock %}

bots/templates/bots/logfiler.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Bots Log File Viewer</title>
    <META Http-Equiv="Pragma" Content="no-cache" />
</head>
{% load i18n %}
<body>
    {% if error_content %} 
        {{ error_content }} 
    {% else %}
        <table id="log" border="1" cellpadding=5>
            <tr>
                <td><b>logfiles</b></td>
                <td><b>{{ log }}</b>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/logfiler/?log={{ log }}&amp;action=download">{% trans 'Download' %}</a></td>
            </tr>
            <tr>
                <td valign="top">
                    {% for file in logfiles %}
                        <a href="/logfiler/?log={{ file }}">{{ file }}</a><br>
                    {% endfor %}
                </td>
                <td valign="top" colspan="2">
                    <pre>{{ logdata }}</pre>
                </td>
            </tr>
        </table>
    {% endif %}
</body>
</html>
 

bots/templates/bots/menu.html
{% load i18n %}
<div id="menu">
{% if user.is_authenticated %}
	<ul>
		<a {% if not bots_touchscreen %} href="/home" {% endif %} >{% trans 'Home' %}</a>
		<li><a href="/home/">{% trans 'Home' %}{% if not bots_touchscreen %} *{% endif %}</a></li>
		<li><a href="http://code.google.com/p/bots/wiki/MonitorIntroduction">{% trans 'Help' %}</a></li>
		<li><a href="/logout/">{% trans 'Log out' %}</a></li>
		<li><a href="/password_change/">{% trans 'Change password' %}</a></li>
	</ul>
	<ul>
		<a {% if not bots_touchscreen %} href="/incoming/?lastrun=1" {% endif %} >{% trans 'Last run' %}</a>
		<li><a href="/incoming/?lastrun=1" >{% trans 'Incoming' %}{% if not bots_touchscreen %} *{% endif %}</a></li>
		<li><a href="/document/?lastrun=1;status=320" >{% trans 'Document-in' %}</a></li>
		<li><a href="/document/?lastrun=1;status=330" >{% trans 'Document-out' %}</a></li>
		<li><a href="/outgoing/?lastrun=1" >{% trans 'Outgoing' %}</a></li>
		<li><a href="/processes/?lastrun=1" >{% trans 'Process Errors' %}</a></li>
	</ul>
	<ul>
		<a {% if not bots_touchscreen %} href="/reports/?lastrun=0" {% endif %} >{% trans 'All runs' %}</a>
		<li><a href="/reports/?lastrun=0" >{% trans 'Report (per run)' %}{% if not bots_touchscreen %} *{% endif %}</a></li>
        <li><a href="/incoming/?lastrun=0" >{% trans 'Incoming' %}</a></li>
		<li><a href="/document/?lastrun=0;status=320" >{% trans 'Document-in' %}</a></li>
		<li><a href="/document/?lastrun=0;status=330" >{% trans 'Document-out' %}</a></li>
		<li><a href="/outgoing/?lastrun=0" >{% trans 'Outgoing' %}</a></li>
		<li><a href="/confirm/?lastrun=0" >{% trans 'Confirmations' %}</a></li>
		<li><a href="/processes/?lastrun=0" >{% trans 'Process Errors' %}</a></li>
	</ul>
	<ul>
		<a {% if not bots_touchscreen %} href="/document/?select" {% endif %} >{% trans 'Select' %}</a>
		<li><a href="/reports/?select" >{% trans 'Reports (per run)' %}</a></li>
        <li><a href="/incoming/?select" >{% trans 'Incoming' %}</a></li>
		<li><a href="/document/?select" >{% trans 'Document' %}{% if not bots_touchscreen %} *{% endif %}</a></li>
		<li><a href="/outgoing/?select" >{% trans 'Outgoing' %}</a></li>
		<li><a href="/processes/?select" >{% trans 'Process Errors' %}</a></li>
		<li><a href="/confirm/?select" >{% trans 'Confirmations' %}</a></li>
	</ul>
	{% if user.is_staff %}
	<ul>
		<a>{% trans 'Configuration' %}</a>
		{% if perms.bots.change_routes %}<li><a href="/admin/bots/routes/" >{% trans 'Routes' %}</a></li>{% endif %}
		{% if perms.bots.change_channel %}<li><a href="/admin/bots/channel/" >{% trans 'Channels' %}</a></li>{% endif %}
		{% if perms.bots.change_translate %}<li><a href="/admin/bots/translate/" >{% trans 'Translations' %}</a></li>{% endif %}
		{% if perms.bots.change_partner %}<li><a href="/admin/bots/partner/" >{% trans 'Partners' %}</a></li>{% endif %}
		{% if perms.bots.change_partner %}<li><a href="/admin/bots/partnergroep/" >{% trans 'Partnergroups' %}</a></li>{% endif %}
		{% if perms.bots.change_confirmrule %}<li><a href="/admin/bots/confirmrule/" >{% trans 'Confirmrules' %}</a></li>{% endif %}
        <li><hr/></li>
		{% if perms.bots.change_ccode %}<li><a href="/admin/bots/ccode/" >{% trans 'User Codes list' %}</a></li>{% endif %}
		{% if perms.bots.change_ccodetrigger %}<li><a href="/admin/bots/ccodetrigger/" >{% trans 'User Code types' %}</a></li>{% endif %}
	</ul>
    {% endif %}
    {% if user.is_superuser %}
	<ul>
		<a>{% trans 'SysTasks' %}</a>
		<li><a href="/plugin/" >{% trans 'Read plugin' %}</a></li>
		<li><a href="/plugout/" >{% trans 'Make plugin' %}</a></li>
		<li><a href="/plugout/backup" >{% trans 'Make backup plugin' %}</a></li>
        <li><hr/></li>
		<li><a href="/plugin/index" >{% trans 'Read configuration index' %}</a></li>
		<li><a href="/plugout/index" >{% trans 'Make configuration index' %}</a></li>
        <li><hr/></li>
		<li><a href="/delete/" >{% trans 'Bulk delete' %}</a></li>
        <li><hr/></li>
		<li><a href="/admin/auth/user/" >{% trans 'Users' %}</a></li>
		<li><a href="/admin/auth/group/" >{% trans 'UserGroups' %}</a></li>
        <li><hr/></li>
		<li><a href="/admin/bots/uniek/" >{% trans 'View/edit counters' %}</a></li>
		<li><a href="/sendtestmail/">{% trans 'Send test report' %}</a></li>
	</ul>
    {% endif %}
	{% if perms.bots.change_mutex %} <!-- change mutex permission is required to run bots-engine! -->
	<ul>
		<a>{% trans 'Run' %}</a>
		<li><a href="/runengine/?clparameter=--new" >{% trans 'Run (only new)' %}</a></li>
        <li><hr/></li>
		<li><a href="/runengine/?clparameter=--rereceive" >{% trans 'Run user-indicated rereceives' %}</a></li>
		<li><a href="/runengine/?clparameter=--resend" >{% trans 'Run user-indicated resends' %}</a></li>
        {% if menu_automaticretrycommunication %}
			<li><a href="/runengine/?clparameter=--automaticretrycommunication" >{% trans 'Retry failed out-communications' %}</a></li>
        {% endif %}
        {% if menu_all_routes %}
            <li><hr/></li>
            {% for route in menu_all_routes %}
                <li><a href="/runengine/?clparameter={{ route|urlencode:'' }}" >{{ route }}</a></li>
            {% endfor %}
        {% endif %}
    </ul>
	{% endif %}
	{% if custom_menus %}
	<ul>
		<a>{{ custom_menuname }}</a>
		{% for key,value in custom_menus %}
			{% ifequal '---' value %}
				<li><hr/></li>
			{% else %}
				<li><a href="{{ value }}" >{{ key }}</a></li>
			{% endifequal %}
		{% endfor %}
    </ul>
	{% endif %}

{% else %}
	<ul>
		<a href="/login/">{% trans 'Log in' %}</a>
	</ul>
{% endif %}
		<noscript>{% trans '*****Javascript is not enabled. Bots works better with javascript*****' %}</noscript>
</div>

bots/templates/bots/paginator.html
{% load i18n %}
    {% if queryset.has_previous %}
        <input type="submit" name="first" value="&lt;&lt;" />
        <input type="submit" name="previous" value="&lt;" />
    {% else %}
        <input disabled type="submit" name="first" value="&lt;&lt;" />
        <input disabled type="submit" name="previous" value="&lt;" />
    {% endif %}
    ({% trans 'Page' %} {{ queryset.number }} {% trans 'of' %} {{ queryset.paginator.num_pages }}; {{ queryset.paginator.count }} {% trans 'items' %})
    {% if queryset.has_next %}
        <input type="submit" name="next" value="&gt;" />
        <input type="submit" name="last" value="&gt;&gt;" />
    {% else %}
        <input disabled type="submit" name="next" value="&gt;" />
        <input disabled type="submit" name="last" value="&gt;&gt;" />
    {% endif %}